/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
import type { Checked, Check } from "./types.js"
import type {  CompanyAddress,  CompanyInfo,  CuratedOffersAndFAQs,  ExtractedFaq,  ExtractedOffering,  ExtractedPrice,  OperationHour,  PageSummary,  RankedPages } from "./types.js"
import type * as types from "./types.js"

/******************************************************************************
*
*  These types are used for streaming, for when an instance of a type
*  is still being built up and any of its fields is not yet fully available.
*
******************************************************************************/

export interface StreamState<T> {
  value: T
  state: "Pending" | "Incomplete" | "Complete"
}

export namespace partial_types {
    export interface CompanyAddress {
      streetAddress?: string | null
      city?: string | null
      state?: string | null
      postalCode?: string | null
      country?: string | null
    }
    export interface CompanyInfo {
      name?: string | null
      email?: string | null
      address?: CompanyAddress | null
      phone?: string | null
    }
    export interface CuratedOffersAndFAQs {
      faqs: ExtractedFaq[]
      offerings: ExtractedOffering[]
    }
    export interface ExtractedFaq {
      question?: string | null
      answer?: string | null
    }
    export interface ExtractedOffering {
      type?: "product" | "service" | null
      name?: string | null
      description?: string | null
      price?: ExtractedPrice | null
    }
    export interface ExtractedPrice {
      amount?: string | null
      currency?: string | null
      frequency?: "one_time" | "hourly" | "daily" | "weekly" | "monthly" | "yearly" | null
    }
    export interface OperationHour {
      dayOfWeek?: number | null
      openTime?: string | null
      closeTime?: string | null
    }
    export interface PageSummary {
      url?: string | null
      title?: string | null
      description?: string | null
    }
    export interface RankedPages {
      faq_urls: string[]
      offering_urls: string[]
    }
}